### ISSUE TITLE
When there is any unpublished content, umbNav breaks: Failed to convert Meganav {ex}

### ISSUE THREAD

**Issue by mrrm** [AaronSadlerUK/Our.Umbraco.UmbNav#63]
### Which *exact* Umbraco version are you using? For example: 8.7.0 - don't just write v8 or v9

8.16

### Bug summary

When the global nav contains unpublished items, the navigation disappears

Failed to convert Meganav "System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Web.PublishedContentExtensions.GetCultureFromDomains(IPublishedContent content, Uri current) in D:\a\1\s\src\Umbraco.Web\PublishedContentExtensions.cs:line 202
   at AaronSadler.MegaNavV8.Core.ValueConverters.MeganavV8ValueConverter.BuildMenu(IEnumerable`1 items, Int32 level)
   at AaronSadler.MegaNavV8.Core.ValueConverters.MeganavV8ValueConverter.BuildMenu(IEnumerable`1 items, Int32 level)
   at AaronSadler.MegaNavV8.Core.ValueConverters.MeganavV8ValueConverter.BuildMenu(IEnumerable`1 items, Int32 level)
   at AaronSadler.MegaNavV8.Core.ValueConverters.MeganavV8ValueConverter.ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview)"

### Specifics

Tested in Chrome and Firefox

### Steps to reproduce

Create a navigation map where a page is unpublished

### Expected result / actual result
Expected: When there is an unpublished page in the navigation, it just musn´t be showed in the menu, not break the navigation menu
Actual: Instead of returning {System.Linq.Enumerable.WhereListIterator<AaronSadler.MegaNavV8.Core.Models.MeganavV8Item>} it returns {AaronSadler.MegaNavV8.Core.Models.MeganavV8Item[0]} despite many others published pages in the navigation
Actual:

**Comment by AaronSadlerUK** [comment]
Sorry for the delay, I will look into this today 🙂

**Comment by AaronSadlerUK** [comment]
@mrrm Can you confirm you are using the latest version of **UmbNav** and not **MegaNavV8**

UmbNav superseeded MegaNavV8 early last year

**Comment by mrrm** [comment]
Hi @AaronSadlerUK . I've tried with the latest version of UmbNav as well. Same issue with unpublished pages in the menu.

**Comment by AaronSadlerUK** [comment]
@mrrm I haven't been able to replicate this, I have added an additional check in 1.1.1 (which i released within the last half hour) try that.

Otherwise I'll need more info / examples to debug further

**Comment by mrrm** [comment]
@AaronSadlerUK thanks. this issue got away when I updated the package
